#route:
#    receiver: 'slack'
#
#receivers:
#    - name: 'slack'
#      slack_configs:
#          - send_resolved: true
#            username: '<username>'
#            channel: '#<channel-name>'
#            api_url: '<incomming-webhook-url>'
#
route:
 group_by: [cluster]
 # If an alert isn't caught by a route, send it to the pager.
 receiver: team-pager
 routes:
  # Send severity=page alerts to the pager.
  - match:
      severity: page
    receiver: team-pager

#receivers:
#- name: team-pager
#  pagerduty_configs:
#  - service_key: 02fef9f58e8c4749b4422491b7a2773a
#    details: {firing: testing template}
#

#receivers:
#- name: team-pager
#  pagerduty_configs:
#  - service_key: 02fef9f58e8c4749b4422491b7a2773a
#    description: 'RabbitMQ{{ template "pagerduty.test" .  }}'

receivers:
- name: team-pager
  pagerduty_configs:
  - service_key: 02fef9f58e8c4749b4422491b7a2773a
#    description: '{{ template "pagerdutytest" . }}{{ define "pagerdutytest"  }}{{ template "pagerduty.default.description" .  }}{{ end  }}' 
#    description: '{{ template "pagerdutytest" . }}{{ define "pagerdutytest"  }}{{ with .CommonLabels.Remove .GroupLabels.Names  }}{{ .Values  | join " "  }}{{ end  }}{{ end  }}'
#    description: '{{ template "pagerdutytest" . }}{{ define "pagerdutytest"  }}{{ range $index, $topping :=  .GroupLabels.Names }}{{ if eq $index "instance" $topping }}{{ end  }}{{ end  }}{{ end  }}'
#    description: '{{ template "pagerdutytest" .  }}{{ define "pagerdutytest"   }}{{ with .CommonLabels.Remove .GroupLabels.Names   }}{{ range $key, $value := .Values   }}{{ $key  }}{{ end  }}{{ end  }}{{ end  }}'
    description: '{{ template "pagerdutytest" .  }}{{ define "pagerdutytest"   }}{{ with .CommonLabels.Remove .GroupLabels.Names   }}{{ range $key, $value := .Values   }}{{ if eq  $key 3  }} {{ $value  }} {{ end  }}{{ end  }}{{ end   }}{{ end   }}'

#receivers:
#- name: team-pager
#  pagerduty_configs:
#  - service_key: 02fef9f58e8c4749b4422491b7a2773a
#    description: Test {{ template "pagerduty.default.description" . }}
#
#receivers:
#- name: team-pager
#  pagerduty_configs:
#  - service_key: 02fef9f58e8c4749b4422491b7a2773a
#    details: {firing: '{{ template "pagerduty.test" .Alerts.Firing }}'}

#templates:
#- '/etc/alertmanager/templates/myorg.tmpl'
